> jetsOutput.txt
nohup python selectionPlots.py -i Zee_MV0_70_BF -o Zee_MV0_70_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV0_70_CFBV -o Zee_MV0_70_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV0_70_CVBV -o Zee_MV0_70_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV1000_E_CMS -o Zee_MV1000_E_CMS-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV140_280_BF -o Zee_MV140_280_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV140_280_CFBV -o Zee_MV140_280_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV140_280_CVBV -o Zee_MV140_280_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV280_500_BF -o Zee_MV280_500_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV280_500_CFBV -o Zee_MV280_500_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV280_500_CVBV -o Zee_MV280_500_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV500_1000 -o Zee_MV500_1000-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV70_140_BF -o Zee_MV70_140_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV70_140_CFBV -o Zee_MV70_140_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zee_MV70_140_CVBV -o Zee_MV70_140_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV0_70_BF -o Zmumu_MV0_70_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV0_70_CFBV.D1 -o Zmumu_MV0_70_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV0_70_CVBV.D1 -o Zmumu_MV0_70_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV1000_E_CMS -o Zmumu_MV1000_E_CMS-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV140_280_BF -o Zmumu_MV140_280_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV140_280_CFBV -o Zmumu_MV140_280_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV140_280_CVBV -o Zmumu_MV140_280_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV280_500_BF -o Zmumu_MV280_500_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV280_500_CFBV -o Zmumu_MV280_500_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV280_500_CVBV -o Zmumu_MV280_500_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV500_1000 -o Zmumu_MV500_1000-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV70_140_BF -o Zmumu_MV70_140_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV70_140_CFBV -o Zmumu_MV70_140_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Zmumu_MV70_140_CVBV -o Zmumu_MV70_140_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV0_70_l13l7 -o Ztt_MV0_70_l13l7-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV0_70_l15h20 -o Ztt_MV0_70_l15h20-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV1000_E_CMS -o Ztt_MV1000_E_CMS-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV280_500_BF -o Ztt_MV280_500_BF-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV280_500_CFBV -o Ztt_MV280_500_CFBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV280_500_CVBV -o Ztt_MV280_500_CVBV-weighted.root >> jetsOutput.txt &
nohup python selectionPlots.py -i Ztt_MV500_1000 -o Ztt_MV500_1000-weighted.root >> jetsOutput.txt &
